[package]
name = "cedar-github-model-app"
edition = "2021"
version = "0.1.0"
publish = false

[dependencies]
clap = { version = "3.1.5", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
anyhow = "1.0"

[dependencies.cedar-policy]
version = "2.0.0"
