name: Build and test Java Partial Evaluation example
on:
  workflow_call:
    inputs:
      cedar_java_ref:
        required: true
        type: string
      cedar_examples_ref:
        required: true
        type: string

jobs:
  build_and_test_java_partial_evaluation:
    name: Build and test Java Partial Evaluation example
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
    steps:
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'
      - name: Checkout cedar-examples
        uses: actions/checkout@v4
        with:
          repository: mudit-chaudhary/cedar-examples
          ref: ${{ inputs.cedar_examples_ref }}
      - name: Build cedar-java-partial-evaluation
        working-directory: ./cedar-java-partial-evaluation
        run: ./gradlew build
      - name: Test cedar-java-partial-evaluation
        working-directory: ./cedar-java-partial-evaluation
        run: ./gradlew test
